title = 'Learning Rust'
baseURL = 'https://learning-rust.github.io/'

defaultContentLanguage = 'en'
languageCode = 'en-us'

googleAnalytics = 'G-FZHQCXSZ89'

enableGitInfo = true

theme = 'docura'

markup.highlight.noClasses = false