title: Learning Rust
subtitle: "Rust Programming Language Tutorials"
description: "Rust Programming Language Tutorials"
author: Dumindu Madunuwan
language: en
timezone: UTC

url: https://learning-rust.github.io
root: /
theme: navy
deploy:
  type: git
  repo: git@github.com:learning-rust/learning-rust.github.io.git

highlight:
  enable: true
  line_number: false

google_analytics: XXXXX-Y
algolia:
  en:
    api_key: xxxxxxxxxxxxxxxx
    index_name: xxxx
github: learning-rust/learning-rust.github.io
